### ISSUE TITLE
Injection might fail on some circumstances

### ISSUE THREAD

**Issue by SayakaIsBaka** [SayakaIsBaka/LR2Arena#1]
DLL injection might fail sometimes, thus rendering the program unusuable for the time being

Still looking into why it does that

**Comment by luxurya111** [comment]
In My Case:
OS: Windows 10

now set to:
1. Windows Locale is Japanese
2. Run as administrator and turn off antivirus(windows defender)
3. add to exclude file/folder list in antivirus
4. Run in LR2SD and HD both

**Comment by SayakaIsBaka** [comment]
DLL loading fails because I inadvertently compiled the DLL in debug mode... That means the DLL is looking for debug runtimes, which aren't included in the redistributable package

Fix is to wait for me to recompile the dll in release mode or manually grab the dlls from the internet (don't do that, or if you really want to, find the missing DLLs using Process Monitor or Dependency Walker)

**Comment by SayakaIsBaka** [comment]
Updated release zip with the proper DLL (there are no new features): https://github.com/SayakaIsBaka/LR2Arena/releases/tag/0.0.1
